# Generated by Django 2.2 on 2019-05-19 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.IntegerField(unique=True)),
                ('name', models.CharField(default='', max_length=50)),
                ('galaxy_name', models.CharField(default='', max_length=50)),
                ('mass', models.CharField(default='', max_length=50)),
                ('mean_radius', models.CharField(default='', max_length=50)),
                ('number_of_stars', models.IntegerField(default=0)),
                ('mean_temperature', models.FloatField(default=0.0)),
                ('average_orbital_speed', models.FloatField(default=0.0)),
                ('pressure', models.FloatField(default=0.0)),
                ('discoverer', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
